"""
Covariate and feature engineering (Part 5).

Adds time-based features (always known in advance), lag features and
rolling statistics of the target (computed strictly from past values),
and passes through the sensor/weather columns already in the dataset.

Leakage safety: every lag/rolling feature is built from
``series.shift(1).rolling(...)`` or ``series.shift(lag)`` with lag >= 1,
so a feature row at time t never reads the value of Appliances at time
t or later. This is asserted in tests/test_features.py.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from . import config


def add_time_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add hour-of-day, day-of-week, weekend indicator, and their cyclic
    (sine/cosine) encodings. These are always known at the forecast
    origin for any future timestamp, since they are deterministic
    functions of the calendar.
    """
    out = df.copy()

    out["hour"] = out.index.hour
    out["dayofweek"] = out.index.dayofweek
    out["is_weekend"] = (out["dayofweek"] >= 5).astype(int)

    out["hour_sin"] = np.sin(2 * np.pi * out["hour"] / 24)
    out["hour_cos"] = np.cos(2 * np.pi * out["hour"] / 24)

    out["dow_sin"] = np.sin(2 * np.pi * out["dayofweek"] / 7)
    out["dow_cos"] = np.cos(2 * np.pi * out["dayofweek"] / 7)

    return out


def add_lag_features(
    df: pd.DataFrame, target: str = config.TARGET, lags: list[int] = config.LAG_HOURS
) -> pd.DataFrame:
    """Add lagged target values. lag_k = Appliances value k hours ago."""
    out = df.copy()
    for lag in lags:
        out[f"lag_{lag}"] = out[target].shift(lag)
    return out


def add_rolling_features(
    df: pd.DataFrame,
    target: str = config.TARGET,
    windows: list[int] = config.ROLLING_WINDOWS,
) -> pd.DataFrame:
    """
    Add rolling mean/std of the target over each window in ``windows``.

    The target is shifted by 1 before rolling so the window ending "now"
    only uses values strictly before the current timestamp - otherwise
    the current (unobserved, to-be-forecast) value would leak into its
    own feature.
    """
    out = df.copy()
    shifted = out[target].shift(1)

    for window in windows:
        out[f"roll_mean_{window}"] = shifted.rolling(window).mean()
        out[f"roll_std_{window}"] = shifted.rolling(window).std()

    return out


# Named feature groups, used both to build the full feature table and to
# run the feature-group ablation study (Part 9, Q3).
FEATURE_GROUPS = {
    "lags": [f"lag_{lag}" for lag in config.LAG_HOURS],
    "rolling": [
        f"roll_{stat}_{w}" for w in config.ROLLING_WINDOWS for stat in ("mean", "std")
    ],
    "time": ["hour", "dayofweek", "is_weekend", "hour_sin", "hour_cos", "dow_sin", "dow_cos"],
    "sensor": config.INDOOR_TEMP_COLS + config.INDOOR_HUMIDITY_COLS,
    "weather": config.OUTDOOR_WEATHER_COLS,
}


def make_feature_table(
    df: pd.DataFrame,
    target: str = config.TARGET,
    lags: list[int] = config.LAG_HOURS,
    windows: list[int] = config.ROLLING_WINDOWS,
    groups: list[str] | None = None,
) -> pd.DataFrame:
    """
    Build the full supervised-learning feature table.

    Parameters
    ----------
    groups:
        Subset of FEATURE_GROUPS keys to include (besides the target
        itself). Defaults to all groups; used by the ablation study to
        build reduced feature sets, e.g. groups=["lags"] for a
        lags-only model.

    Returns
    -------
    Dataframe indexed like ``df``, containing the target column plus
    every requested feature column, with the initial rows that don't
    have full lag/rolling history dropped (NaNs from shifting).
    """
    if groups is None:
        groups = list(FEATURE_GROUPS.keys())

    base = df[[target]].copy()

    if "time" in groups:
        base = add_time_features(base)

    if "lags" in groups:
        base = add_lag_features(base, target, lags)

    if "rolling" in groups:
        base = add_rolling_features(base, target, windows)

    if "sensor" in groups:
        sensor_cols = [c for c in FEATURE_GROUPS["sensor"] if c in df.columns]
        base = base.join(df[sensor_cols])

    if "weather" in groups:
        weather_cols = [c for c in FEATURE_GROUPS["weather"] if c in df.columns]
        base = base.join(df[weather_cols])

    return base.dropna()


def feature_columns_for_groups(groups: list[str], df_columns: list[str]) -> list[str]:
    """
    Return the concrete feature-column names for a set of feature groups
    that are actually present in ``df_columns`` (lags/rolling/time are
    always generated by make_feature_table, so always present; sensor/
    weather columns depend on what the raw dataset contains).
    """
    cols = []
    for g in groups:
        cols.extend([c for c in FEATURE_GROUPS[g] if c in df_columns])
    return cols
